/**
 * Server copy of the 2027 exam table, for Netlify functions (which can't import
 * src/, an ES module with browser-only imports). Main sitting date only.
 *
 * NOT the source of truth: src/constants/apExamDates.js is. weeklyDigest.test.js
 * fails if these drift apart, so the annual rollover has to update both.
 */

const SUBJECT_KEY_TO_EXAM_NAME = {
  "artHistory": "AP Art History",
  "biology": "AP Biology",
  "calculusAB": "AP Calculus AB",
  "calculusBC": "AP Calculus BC",
  "chemistry": "AP Chemistry",
  "chineseLanguage": "AP Chinese Language and Culture",
  "computerScienceA": "AP Computer Science A",
  "computerSciencePrinciples": "AP Computer Science Principles",
  "englishLanguageAndComposition": "AP English Language and Composition",
  "englishLiteratureAndComposition": "AP English Literature and Composition",
  "environmentalScience": "AP Environmental Science",
  "europeanHistory": "AP European History",
  "frenchLanguage": "AP French Language and Culture",
  "germanLanguage": "AP German Language and Culture",
  "comparativeGovernment": "AP Government and Politics: Comparative",
  "usGovernmentPolitics": "AP U.S. Government and Politics",
  "humanGeography": "AP Human Geography",
  "italianLanguage": "AP Italian Language and Culture",
  "japaneseLanguage": "AP Japanese Language and Culture",
  "latin": "AP Latin",
  "macroeconomics": "AP Macroeconomics",
  "microeconomics": "AP Microeconomics",
  "musicTheory": "AP Music Theory",
  "physics1": "AP Physics 1: Algebra-Based",
  "physics2": "AP Physics 2: Algebra-Based",
  "physicsC_Mechanics": "AP Physics C: Mechanics",
  "physicsC_ElectricityMagnetism": "AP Physics C: Electricity and Magnetism",
  "precalculus": "AP Precalculus",
  "psychology": "AP Psychology",
  "research": "AP Research",
  "seminar": "AP Seminar",
  "spanishLanguage": "AP Spanish Language and Culture",
  "spanishLiterature": "AP Spanish Literature and Culture",
  "statistics": "AP Statistics",
  "studioArt2D": "AP Studio Art: 2-D Design",
  "studioArt3D": "AP Studio Art: 3-D Design",
  "studioArtDrawing": "AP Studio Art: Drawing",
  "usHistory": "AP U.S. History",
  "worldHistory": "AP World History: Modern",
  "africanAmericanStudies": "AP African American Studies",
  "businessPersonalFinance": "AP Business with Personal Finance",
  "cybersecurity": "AP Cybersecurity",
  "studioArt": "AP Art and Design",
};

const EXAM_DATES = {
  "AP Human Geography": "2027-05-03",
  "AP Physics C: Mechanics": "2027-05-03",
  "AP Biology": "2027-05-03",
  "AP Italian Language and Culture": "2027-05-03",
  "AP Business with Personal Finance": "2027-05-04",
  "AP U.S. Government and Politics": "2027-05-04",
  "AP European History": "2027-05-04",
  "AP Microeconomics": "2027-05-04",
  "AP Cybersecurity": "2027-05-05",
  "AP English Literature and Composition": "2027-05-05",
  "AP Physics 1: Algebra-Based": "2027-05-05",
  "AP Physics C: Electricity and Magnetism": "2027-05-05",
  "AP French Language and Culture": "2027-05-06",
  "AP Physics 2: Algebra-Based": "2027-05-06",
  "AP World History: Modern": "2027-05-06",
  "AP African American Studies": "2027-05-06",
  "AP Chemistry": "2027-05-06",
  "AP German Language and Culture": "2027-05-07",
  "AP U.S. History": "2027-05-07",
  "AP Macroeconomics": "2027-05-07",
  "AP Networking": "2027-05-07",
  "AP Calculus AB": "2027-05-10",
  "AP Calculus BC": "2027-05-10",
  "AP Music Theory": "2027-05-10",
  "AP Seminar": "2027-05-10",
  "AP Japanese Language and Culture": "2027-05-11",
  "AP Precalculus": "2027-05-11",
  "AP Statistics": "2027-05-11",
  "AP English Language and Composition": "2027-05-12",
  "AP Art History": "2027-05-12",
  "AP Computer Science A": "2027-05-12",
  "AP Spanish Language and Culture": "2027-05-13",
  "AP Chinese Language and Culture": "2027-05-13",
  "AP Environmental Science": "2027-05-13",
  "AP Government and Politics: Comparative": "2027-05-14",
  "AP Computer Science Principles": "2027-05-14",
  "AP Spanish Literature and Culture": "2027-05-14",
  "AP Latin": "2027-05-14",
  "AP Psychology": "2027-05-14",
  "AP Art and Design": "2027-05-07",
  "AP Studio Art: 2-D Design": "2027-05-07",
  "AP Studio Art: 3-D Design": "2027-05-07",
  "AP Studio Art: Drawing": "2027-05-07",
  "AP Research": "2027-04-30",
};

module.exports = { SUBJECT_KEY_TO_EXAM_NAME, EXAM_DATES };
