export const AP_SUBJECTS = {
    "AP Biology": { name: "AP Biology", description: "Dive into the science of living organisms.", icon: "🔬" },
    "AP Calculus AB": { name: "AP Calculus AB", description: "Master derivatives, integrals, and limits.", icon: "∫" },
    "AP Calculus BC": { name: "AP Calculus BC", description: "Advanced topics in calculus.", icon: "∬" },
    "AP Chemistry": { name: "AP Chemistry", description: "Understand the composition of matter.", icon: "🧪" },
    "AP Chinese Language and Culture": { name: "AP Chinese", description: "Develop your Chinese language skills.", icon: "中文" },
    "AP Computer Science A": { name: "AP Computer Science A", description: "Learn Java and object-oriented programming.", icon: "💻" },
    "AP Computer Science Principles": { name: "AP CS Principles", description: "Learn the basics of computer science.", icon: "💻" },
    "AP English Language and Composition": { name: "AP English Language", description: "Analyze rhetoric and compose arguments.", icon: "✍️" },
    "AP English Literature and Composition": { name: "AP English Literature", description: "Study and interpret literary works.", icon: "📚" },
    "AP Environmental Science": { name: "AP Environmental Science", description: "Examine the natural world and its challenges.", icon: "🌍" },
    "AP European History": { name: "AP European History", description: "Journey through Europe's past.", icon: "🏰" },
    "AP French Language and Culture": { name: "AP French", description: "Enhance your French proficiency.", icon: "🇫🇷" },
    "AP German Language and Culture": { name: "AP German", description: "Enhance your German proficiency.", icon: "🇩🇪" },
    "AP Government and Politics: Comparative": { name: "AP Comparative Government", description: "Compare and contrast different political systems.", icon: "🏛" },
    "AP Human Geography": { name: "AP Human Geography", description: "Study human populations and cultures.", icon: "🗺️" },
    "AP Italian Language and Culture": { name: "AP Italian", description: "Immerse yourself in Italian language.", icon: "🇮🇹" },
    "AP Japanese Language and Culture": { name: "AP Japanese", description: "Explore Japanese language and society.", icon: "日本" },
    "AP Latin": { name: "AP Latin", description: "Read and analyze classical texts.", icon: "🏛️" },
    "AP Macroeconomics": { name: "AP Macroeconomics", description: "Study economy-wide phenomena.", icon: "📈" },
    "AP Microeconomics": { name: "AP Microeconomics", description: "Analyze individual economic decisions.", icon: "📉" },
    "AP Physics 1: Algebra-Based": { name: "AP Physics 1", description: "Explore the fundamental principles of physics.", icon: "🔬" },
    "AP Physics 2: Algebra-Based": { name: "AP Physics 2", description: "Advanced physics concepts and applications.", icon: "⚛️" },
    "AP Physics C: Mechanics": { name: "AP Physics C: Mechanics", description: "Delve into classical mechanics with calculus.", icon: "📐" },
    "AP Physics C: Electricity and Magnetism": { name: "AP Physics C: E&M", description: "Master electromagnetism with calculus.", icon: "⚡" },
    "AP Psychology": { name: "AP Psychology", description: "Investigate the human mind and behavior.", icon: "🧠" },
    "AP Spanish Language and Culture": { name: "AP Spanish Language", description: "Master the Spanish language.", icon: "🇪🇸" },
    "AP Spanish Literature and Culture": { name: "AP Spanish Literature", description: "Explore Spanish literature and culture.", icon: "📖" },
    "AP Statistics": { name: "AP Statistics", description: "Learn to collect, analyze, and interpret data.", icon: "📊" },
    "AP U.S. Government and Politics": { name: "AP US Government", description: "Understand the American political system.", icon: "🇺🇸" },
    "AP U.S. History": { name: "AP US History", description: "Explore the history of the United States.", icon: "🦅" },
    "AP World History: Modern": { name: "AP World History", description: "Examine global history from 1200 CE.", icon: "🌐" },
};

// Default export for backwards compatibility
export const subjects = AP_SUBJECTS;
export default AP_SUBJECTS;
